version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    networks:
      - app_network

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "5252:5252"
    networks:
      - app_network

  proxy:
    build: ./proxy
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - frontend
      - backend
